// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz3QvpxKgtmU9mCFG2rkY5JQ_CYjxkJfk',
    appId: '1:948551781701:web:1a7b5136f79793e713422c',
    messagingSenderId: '948551781701',
    projectId: 'pushnotification-92038',
    authDomain: 'pushnotification-92038.firebaseapp.com',
    storageBucket: 'pushnotification-92038.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFKZUTmAbA2caBSSp3rU19IdRH_NJEMXQ',
    appId: '1:948551781701:android:39ac1165c989f28e13422c',
    messagingSenderId: '948551781701',
    projectId: 'pushnotification-92038',
    storageBucket: 'pushnotification-92038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAyrld2C1Vv3AbUnbeaXN6rUNFCahF0XI',
    appId: '1:948551781701:ios:14e18d4efae6df4413422c',
    messagingSenderId: '948551781701',
    projectId: 'pushnotification-92038',
    storageBucket: 'pushnotification-92038.appspot.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAyrld2C1Vv3AbUnbeaXN6rUNFCahF0XI',
    appId: '1:948551781701:ios:9b50edd7e08df27313422c',
    messagingSenderId: '948551781701',
    projectId: 'pushnotification-92038',
    storageBucket: 'pushnotification-92038.appspot.com',
    iosBundleId: 'com.example.pushnotification.RunnerTests',
  );
}
